from __future__ import annotations

import logging
from enum import StrEnum
from typing import Any

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

logger = logging.getLogger(__name__)


class ErrorCode(StrEnum):
    WALLET_NOT_FOUND = "WALLET_NOT_FOUND"
    WALLET_INSUFFICIENT_BALANCE = "WALLET_INSUFFICIENT_BALANCE"
    BILLING_STATE_INVALID = "BILLING_STATE_INVALID"
    BILLING_BUSY = "BILLING_BUSY"
    BILLING_QUOTE_CHANGED = "BILLING_QUOTE_CHANGED"
    PAYMENT_NOT_ENABLED = "PAYMENT_NOT_ENABLED"
    RECHARGE_NOT_FOUND = "RECHARGE_NOT_FOUND"
    RECHARGE_STATE_INVALID = "RECHARGE_STATE_INVALID"
    RECHARGE_LIMIT_REACHED = "RECHARGE_LIMIT_REACHED"
    RECHARGE_REQUEST_CONFLICT = "RECHARGE_REQUEST_CONFLICT"
    RECHARGE_AMOUNT_MISMATCH = "RECHARGE_AMOUNT_MISMATCH"
    RECHARGE_RECEIPT_USED = "RECHARGE_RECEIPT_USED"
    REGISTRATION_DISABLED = "REGISTRATION_DISABLED"
    REGISTRATION_EMAIL_UNAVAILABLE = "REGISTRATION_EMAIL_UNAVAILABLE"
    REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED"
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    REQUEST_FAILED = "REQUEST_FAILED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    API_KEY_NOT_CONFIGURED = "API_KEY_NOT_CONFIGURED"
    API_KEY_INVALID = "API_KEY_INVALID"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_MEMBERSHIP_MISSING = "AUTH_MEMBERSHIP_MISSING"
    AUTH_SESSION_INVALID = "AUTH_SESSION_INVALID"
    AUTH_SESSION_INACTIVE = "AUTH_SESSION_INACTIVE"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_READ_ONLY = "AUTH_READ_ONLY"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    PERSON_NOT_FOUND = "PERSON_NOT_FOUND"
    SUBJECT_NOT_FOUND = "SUBJECT_NOT_FOUND"
    CHAPTER_NOT_FOUND = "CHAPTER_NOT_FOUND"
    INTERVIEW_NOT_FOUND = "INTERVIEW_NOT_FOUND"
    INTERVIEW_INACTIVE = "INTERVIEW_INACTIVE"
    INTERVIEW_ROUND_NOT_FOUND = "INTERVIEW_ROUND_NOT_FOUND"
    INTERVIEW_TURN_CONTENT_REQUIRED = "INTERVIEW_TURN_CONTENT_REQUIRED"
    INTERVIEW_TURN_NOT_FOUND = "INTERVIEW_TURN_NOT_FOUND"
    INTERVIEW_TURN_STATE_INVALID = "INTERVIEW_TURN_STATE_INVALID"
    INTERVIEW_LLM_CONFIGURATION_INCOMPLETE = "INTERVIEW_LLM_CONFIGURATION_INCOMPLETE"
    INTERVIEW_LLM_REQUEST_FAILED = "INTERVIEW_LLM_REQUEST_FAILED"
    INTERVIEW_LLM_RESPONSE_INVALID = "INTERVIEW_LLM_RESPONSE_INVALID"
    EVIDENCE_ASSET_NOT_FOUND = "EVIDENCE_ASSET_NOT_FOUND"
    EVIDENCE_FILE_EMPTY = "EVIDENCE_FILE_EMPTY"
    EVIDENCE_UPLOAD_UNAVAILABLE = "EVIDENCE_UPLOAD_UNAVAILABLE"
    EVIDENCE_UPLOAD_NOT_FOUND = "EVIDENCE_UPLOAD_NOT_FOUND"
    EVIDENCE_UPLOAD_EXPIRED = "EVIDENCE_UPLOAD_EXPIRED"
    EVIDENCE_UPLOAD_INVALID = "EVIDENCE_UPLOAD_INVALID"
    EVIDENCE_UPLOAD_BUSY = "EVIDENCE_UPLOAD_BUSY"
    EVIDENCE_UPLOAD_FAILED = "EVIDENCE_UPLOAD_FAILED"
    EVIDENCE_FILE_TOO_LARGE = "EVIDENCE_FILE_TOO_LARGE"
    EVIDENCE_TYPE_UNSUPPORTED = "EVIDENCE_TYPE_UNSUPPORTED"
    EVIDENCE_RANGE_INVALID = "EVIDENCE_RANGE_INVALID"
    EVIDENCE_ANALYSIS_UNSUPPORTED = "EVIDENCE_ANALYSIS_UNSUPPORTED"
    EVIDENCE_ANALYSIS_FAILED = "EVIDENCE_ANALYSIS_FAILED"
    VISION_CONFIGURATION_INCOMPLETE = "VISION_CONFIGURATION_INCOMPLETE"
    ASR_NOT_CONFIGURED = "ASR_NOT_CONFIGURED"
    ASR_CONFIGURATION_INCOMPLETE = "ASR_CONFIGURATION_INCOMPLETE"
    ASR_REQUEST_FAILED = "ASR_REQUEST_FAILED"
    ASR_EMPTY_TRANSCRIPT = "ASR_EMPTY_TRANSCRIPT"
    TRANSCRIPT_NOT_FOUND = "TRANSCRIPT_NOT_FOUND"
    MEMORY_REVIEW_STATUS_INVALID = "MEMORY_REVIEW_STATUS_INVALID"
    MEMORY_CLAIM_NOT_FOUND = "MEMORY_CLAIM_NOT_FOUND"
    MEMORY_LLM_CONFIGURATION_INCOMPLETE = "MEMORY_LLM_CONFIGURATION_INCOMPLETE"
    MEMORY_LLM_REQUEST_FAILED = "MEMORY_LLM_REQUEST_FAILED"
    MEMORY_LLM_RESPONSE_INVALID = "MEMORY_LLM_RESPONSE_INVALID"
    SCRIPT_PROJECT_NOT_FOUND = "SCRIPT_PROJECT_NOT_FOUND"
    SCRIPT_MEMORIES_REQUIRED = "SCRIPT_MEMORIES_REQUIRED"
    SCRIPT_LLM_CONFIGURATION_INCOMPLETE = "SCRIPT_LLM_CONFIGURATION_INCOMPLETE"
    SCRIPT_LLM_REQUEST_FAILED = "SCRIPT_LLM_REQUEST_FAILED"
    SCRIPT_LLM_RESPONSE_INVALID = "SCRIPT_LLM_RESPONSE_INVALID"
    VISION_REQUEST_FAILED = "VISION_REQUEST_FAILED"
    VISION_RESPONSE_INVALID = "VISION_RESPONSE_INVALID"
    GUARDIAN_CONSENT_REQUIRED = "GUARDIAN_CONSENT_REQUIRED"
    PRODUCTION_CONSENT_REQUIRED = "PRODUCTION_CONSENT_REQUIRED"
    PORTRAIT_CONSENT_REQUIRED = "PORTRAIT_CONSENT_REQUIRED"
    PUBLICATION_CONSENT_REQUIRED = "PUBLICATION_CONSENT_REQUIRED"
    CONSENT_NOT_FOUND = "CONSENT_NOT_FOUND"
    VIDEO_PROVIDER_INVALID = "VIDEO_PROVIDER_INVALID"
    VIDEO_PROVIDER_CONFIGURATION_INCOMPLETE = "VIDEO_PROVIDER_CONFIGURATION_INCOMPLETE"
    VIDEO_PROVIDER_REQUEST_FAILED = "VIDEO_PROVIDER_REQUEST_FAILED"
    VIDEO_PROVIDER_TIMEOUT = "VIDEO_PROVIDER_TIMEOUT"
    VIDEO_PROVIDER_OUTPUT_INVALID = "VIDEO_PROVIDER_OUTPUT_INVALID"
    VIDEO_PROVIDER_FAILED = "VIDEO_PROVIDER_FAILED"
    VIDEO_PLAN_FAILED = "VIDEO_PLAN_FAILED"
    VIDEO_PLAN_INVALID = "VIDEO_PLAN_INVALID"
    VIDEO_PLAN_CONFIGURATION_INCOMPLETE = "VIDEO_PLAN_CONFIGURATION_INCOMPLETE"
    VIDEO_ASSEMBLY_UNAVAILABLE = "VIDEO_ASSEMBLY_UNAVAILABLE"
    VIDEO_ASSEMBLY_FAILED = "VIDEO_ASSEMBLY_FAILED"
    VIDEO_DURATION_UNSUPPORTED = "VIDEO_DURATION_UNSUPPORTED"
    VIDEO_DURATION_MISMATCH = "VIDEO_DURATION_MISMATCH"
    VIDEO_SUBMISSION_UNCERTAIN = "VIDEO_SUBMISSION_UNCERTAIN"
    PRODUCTION_SCRIPT_EMPTY = "PRODUCTION_SCRIPT_EMPTY"
    PRODUCTION_RUN_NOT_FOUND = "PRODUCTION_RUN_NOT_FOUND"
    PRODUCTION_STATE_INVALID = "PRODUCTION_STATE_INVALID"
    PRODUCTION_ASSET_NOT_FOUND = "PRODUCTION_ASSET_NOT_FOUND"
    PRODUCTION_NOT_COMPLETED = "PRODUCTION_NOT_COMPLETED"
    PUBLICATION_AUDIENCE_MISMATCH = "PUBLICATION_AUDIENCE_MISMATCH"
    PUBLICATION_NOT_FOUND = "PUBLICATION_NOT_FOUND"
    PUBLICATION_UNAVAILABLE = "PUBLICATION_UNAVAILABLE"
    PUBLICATION_ASSET_UNAVAILABLE = "PUBLICATION_ASSET_UNAVAILABLE"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_RETRY_NOT_ALLOWED = "JOB_RETRY_NOT_ALLOWED"
    WORKER_ERROR = "WORKER_ERROR"


class ApiError(Exception):
    def __init__(
        self,
        status_code: int,
        code: ErrorCode,
        context: dict[str, Any] | None = None,
    ) -> None:
        self.status_code = status_code
        self.code = code
        self.context = context or {}
        super().__init__(code.value)


def _response(
    status_code: int, code: ErrorCode, context: dict[str, Any] | None = None
) -> JSONResponse:
    error: dict[str, Any] = {"code": code.value}
    if context:
        error["context"] = context
    return JSONResponse(status_code=status_code, content={"error": error})


def install_error_handlers(app: FastAPI) -> None:
    @app.exception_handler(ApiError)
    async def handle_api_error(_: Request, exc: ApiError) -> JSONResponse:
        return _response(exc.status_code, exc.code, exc.context)

    @app.exception_handler(RequestValidationError)
    async def handle_validation_error(_: Request, __: RequestValidationError) -> JSONResponse:
        return _response(422, ErrorCode.REQUEST_VALIDATION_FAILED)

    @app.exception_handler(StarletteHTTPException)
    async def handle_http_error(_: Request, exc: StarletteHTTPException) -> JSONResponse:
        code = {
            404: ErrorCode.ROUTE_NOT_FOUND,
            405: ErrorCode.METHOD_NOT_ALLOWED,
        }.get(exc.status_code, ErrorCode.REQUEST_FAILED)
        return _response(exc.status_code, code)

    @app.exception_handler(Exception)
    async def handle_unexpected_error(request: Request, exc: Exception) -> JSONResponse:
        logger.exception("Unhandled API error on %s", request.url.path, exc_info=exc)
        return _response(500, ErrorCode.INTERNAL_SERVER_ERROR)
